export const locations = {
  "Aceh": [
    "Aceh Barat",
    "Aceh Barat Daya",
    "Aceh Besar",
    "Aceh Jaya",
    "Aceh Selatan",
    "Aceh Singkil",
    "Aceh Tamiang",
    "Aceh Tengah",
    "Aceh Tenggara",
    "Aceh Timur",
    "Aceh Utara",
    "Banda Aceh",
    "Bener Meriah",
    "Bireuen",
    "Gayo Lues",
    "Langsa",
    "Lhokseumawe",
    "Nagan Raya",
    "Pidie",
    "Pidie Jaya",
    "Sabang",
    "Simeulue",
    "Subulussalam"
  ],
  "Sumatera Utara": [
    "Asahan",
    "Batu Bara",
    "Binjai",
    "Dairi",
    "Deli Serdang",
    "Gunungsitoli",
    "Humbang Hasundutan",
    "Karo",
    "Labuhan Batu",
    "Labuhan Batu Selatan",
    "Labuhan Batu Utara",
    "Langkat",
    "Mandailing Natal",
    "Medan",
    "Nias",
    "Nias Barat",
    "Nias Selatan",
    "Nias Utara",
    "Padang Lawas",
    "Padang Lawas Utara",
    "Padangsidimpuan",
    "Pakpak Bharat",
    "Pematang Siantar",
    "Samosir",
    "Serdang Bedagai",
    "Sibolga",
    "Simalungun",
    "Tanjung Balai",
    "Tapanuli Selatan",
    "Tapanuli Tengah",
    "Tapanuli Utara",
    "Tebing Tinggi",
    "Toba Samosir"
  ],
  "Sumatera Barat": [
    "Agam",
    "Bukittinggi",
    "Dharmasraya",
    "Kepulauan Mentawai",
    "Lima Puluh Kota",
    "Padang",
    "Padang Panjang",
    "Padang Pariaman",
    "Pariaman",
    "Pasaman",
    "Pasaman Barat",
    "Payakumbuh",
    "Pesisir Selatan",
    "Sawah Lunto",
    "Sijunjung",
    "Solok",
    "Solok",
    "Solok Selatan",
    "Tanah Datar"
  ],
  "Riau": [
    "Bengkalis",
    "D U M A I",
    "Indragiri Hilir",
    "Indragiri Hulu",
    "Kampar",
    "Kepulauan Meranti",
    "Kuantan Singingi",
    "Pekanbaru",
    "Pelalawan",
    "Rokan Hilir",
    "Rokan Hulu",
    "S I A K"
  ],
  "Jambi": [
    "Batang Hari",
    "Bungo",
    "Jambi",
    "Kerinci",
    "Merangin",
    "Muaro Jambi",
    "Sarolangun",
    "Sungai Penuh",
    "Tanjung Jabung Barat",
    "Tanjung Jabung Timur",
    "Tebo"
  ],
  "Sumatera Selatan": [
    "Banyu Asin",
    "Empat Lawang",
    "Lahat",
    "Lubuklinggau",
    "Muara Enim",
    "Musi Banyuasin",
    "Musi Rawas",
    "Musi Rawas Utara",
    "Ogan Ilir",
    "Ogan Komering Ilir",
    "Ogan Komering Ulu",
    "Ogan Komering Ulu Selatan",
    "Ogan Komering Ulu Timur",
    "Pagar Alam",
    "Palembang",
    "Penukal Abab Lematang Ilir",
    "Prabumulih"
  ],
  "Bengkulu": [
    "Bengkulu",
    "Bengkulu Selatan",
    "Bengkulu Tengah",
    "Bengkulu Utara",
    "Kaur",
    "Kepahiang",
    "Lebong",
    "Mukomuko",
    "Rejang Lebong",
    "Seluma"
  ],
  "Lampung": [
    "Bandar Lampung",
    "Lampung Barat",
    "Lampung Selatan",
    "Lampung Tengah",
    "Lampung Timur",
    "Lampung Utara",
    "Mesuji",
    "Metro",
    "Pesawaran",
    "Pesisir Barat",
    "Pringsewu",
    "Tanggamus",
    "Tulang Bawang Barat",
    "Tulangbawang",
    "Way Kanan"
  ],
  "Kepulauan Bangka Belitung": [
    "Bangka",
    "Bangka Barat",
    "Bangka Selatan",
    "Bangka Tengah",
    "Belitung",
    "Belitung Timur",
    "Pangkal Pinang"
  ],
  "Kepulauan Riau": [
    "B A T A M",
    "Bintan",
    "Karimun",
    "Kepulauan Anambas",
    "Lingga",
    "Natuna",
    "Tanjung Pinang"
  ],
  "Dki Jakarta": [
    "Jakarta Barat",
    "Jakarta Pusat",
    "Jakarta Selatan",
    "Jakarta Timur",
    "Jakarta Utara",
    "Kepulauan Seribu"
  ],
  "Jawa Barat": [
    "Bandung",
    "Bandung",
    "Bandung Barat",
    "Banjar",
    "Bekasi",
    "Bekasi",
    "Bogor",
    "Bogor",
    "Ciamis",
    "Cianjur",
    "Cimahi",
    "Cirebon",
    "Cirebon",
    "Depok",
    "Garut",
    "Indramayu",
    "Karawang",
    "Kuningan",
    "Majalengka",
    "Pangandaran",
    "Purwakarta",
    "Subang",
    "Sukabumi",
    "Sukabumi",
    "Sumedang",
    "Tasikmalaya",
    "Tasikmalaya"
  ],
  "Jawa Tengah": [
    "Banjarnegara",
    "Banyumas",
    "Batang",
    "Blora",
    "Boyolali",
    "Brebes",
    "Cilacap",
    "Demak",
    "Grobogan",
    "Jepara",
    "Karanganyar",
    "Kebumen",
    "Kendal",
    "Klaten",
    "Kudus",
    "Magelang",
    "Magelang",
    "Pati",
    "Pekalongan",
    "Pekalongan",
    "Pemalang",
    "Purbalingga",
    "Purworejo",
    "Rembang",
    "Salatiga",
    "Semarang",
    "Semarang",
    "Sragen",
    "Sukoharjo",
    "Surakarta",
    "Tegal",
    "Tegal",
    "Temanggung",
    "Wonogiri",
    "Wonosobo"
  ],
  "Di Yogyakarta": [
    "Bantul",
    "Gunung Kidul",
    "Kulon Progo",
    "Sleman",
    "Yogyakarta"
  ],
  "Jawa Timur": [
    "Bangkalan",
    "Banyuwangi",
    "Batu",
    "Blitar",
    "Blitar",
    "Bojonegoro",
    "Bondowoso",
    "Gresik",
    "Jember",
    "Jombang",
    "Kediri",
    "Kediri",
    "Lamongan",
    "Lumajang",
    "Madiun",
    "Madiun",
    "Magetan",
    "Malang",
    "Malang",
    "Mojokerto",
    "Mojokerto",
    "Nganjuk",
    "Ngawi",
    "Pacitan",
    "Pamekasan",
    "Pasuruan",
    "Pasuruan",
    "Ponorogo",
    "Probolinggo",
    "Probolinggo",
    "Sampang",
    "Sidoarjo",
    "Situbondo",
    "Sumenep",
    "Surabaya",
    "Trenggalek",
    "Tuban",
    "Tulungagung"
  ],
  "Banten": [
    "Cilegon",
    "Lebak",
    "Pandeglang",
    "Serang",
    "Serang",
    "Tangerang",
    "Tangerang",
    "Tangerang Selatan"
  ],
  "Bali": [
    "Badung",
    "Bangli",
    "Buleleng",
    "Denpasar",
    "Gianyar",
    "Jembrana",
    "Karang Asem",
    "Klungkung",
    "Tabanan"
  ],
  "Nusa Tenggara Barat": [
    "Bima",
    "Bima",
    "Dompu",
    "Lombok Barat",
    "Lombok Tengah",
    "Lombok Timur",
    "Lombok Utara",
    "Mataram",
    "Sumbawa",
    "Sumbawa Barat"
  ],
  "Nusa Tenggara Timur": [
    "Alor",
    "Belu",
    "Ende",
    "Flores Timur",
    "Kupang",
    "Kupang",
    "Lembata",
    "Malaka",
    "Manggarai",
    "Manggarai Barat",
    "Manggarai Timur",
    "Nagekeo",
    "Ngada",
    "Rote Ndao",
    "Sabu Raijua",
    "Sikka",
    "Sumba Barat",
    "Sumba Barat Daya",
    "Sumba Tengah",
    "Sumba Timur",
    "Timor Tengah Selatan",
    "Timor Tengah Utara"
  ],
  "Kalimantan Barat": [
    "Bengkayang",
    "Kapuas Hulu",
    "Kayong Utara",
    "Ketapang",
    "Kubu Raya",
    "Landak",
    "Melawi",
    "Mempawah",
    "Pontianak",
    "Sambas",
    "Sanggau",
    "Sekadau",
    "Singkawang",
    "Sintang"
  ],
  "Kalimantan Tengah": [
    "Barito Selatan",
    "Barito Timur",
    "Barito Utara",
    "Gunung Mas",
    "Kapuas",
    "Katingan",
    "Kotawaringin Barat",
    "Kotawaringin Timur",
    "Lamandau",
    "Murung Raya",
    "Palangka Raya",
    "Pulang Pisau",
    "Seruyan",
    "Sukamara"
  ],
  "Kalimantan Selatan": [
    "Balangan",
    "Banjar",
    "Banjar Baru",
    "Banjarmasin",
    "Barito Kuala",
    "Hulu Sungai Selatan",
    "Hulu Sungai Tengah",
    "Hulu Sungai Utara",
    "Kota Baru",
    "Tabalong",
    "Tanah Bumbu",
    "Tanah Laut",
    "Tapin"
  ],
  "Kalimantan Timur": [
    "Balikpapan",
    "Berau",
    "Bontang",
    "Kutai Barat",
    "Kutai Kartanegara",
    "Kutai Timur",
    "Mahakam Hulu",
    "Paser",
    "Penajam Paser Utara",
    "Samarinda"
  ],
  "Kalimantan Utara": [
    "Bulungan",
    "Malinau",
    "Nunukan",
    "Tana Tidung",
    "Tarakan"
  ],
  "Sulawesi Utara": [
    "Bitung",
    "Bolaang Mongondow",
    "Bolaang Mongondow Selatan",
    "Bolaang Mongondow Timur",
    "Bolaang Mongondow Utara",
    "Kepulauan Sangihe",
    "Kepulauan Talaud",
    "Kotamobagu",
    "Manado",
    "Minahasa",
    "Minahasa Selatan",
    "Minahasa Tenggara",
    "Minahasa Utara",
    "Siau Tagulandang Biaro",
    "Tomohon"
  ],
  "Sulawesi Tengah": [
    "Banggai",
    "Banggai Kepulauan",
    "Banggai Laut",
    "Buol",
    "Donggala",
    "Morowali",
    "Morowali Utara",
    "Palu",
    "Parigi Moutong",
    "Poso",
    "Sigi",
    "Tojo Una-una",
    "Toli-toli"
  ],
  "Sulawesi Selatan": [
    "Bantaeng",
    "Barru",
    "Bone",
    "Bulukumba",
    "Enrekang",
    "Gowa",
    "Jeneponto",
    "Kepulauan Selayar",
    "Luwu",
    "Luwu Timur",
    "Luwu Utara",
    "Makassar",
    "Maros",
    "Palopo",
    "Pangkajene Dan Kepulauan",
    "Parepare",
    "Pinrang",
    "Sidenreng Rappang",
    "Sinjai",
    "Soppeng",
    "Takalar",
    "Tana Toraja",
    "Toraja Utara",
    "Wajo"
  ],
  "Sulawesi Tenggara": [
    "Baubau",
    "Bombana",
    "Buton",
    "Buton Selatan",
    "Buton Tengah",
    "Buton Utara",
    "Kendari",
    "Kolaka",
    "Kolaka Timur",
    "Kolaka Utara",
    "Konawe",
    "Konawe Kepulauan",
    "Konawe Selatan",
    "Konawe Utara",
    "Muna",
    "Muna Barat",
    "Wakatobi"
  ],
  "Gorontalo": [
    "Boalemo",
    "Bone Bolango",
    "Gorontalo",
    "Gorontalo",
    "Gorontalo Utara",
    "Pohuwato"
  ],
  "Sulawesi Barat": [
    "Majene",
    "Mamasa",
    "Mamuju",
    "Mamuju Tengah",
    "Mamuju Utara",
    "Polewali Mandar"
  ],
  "Maluku": [
    "Ambon",
    "Buru",
    "Buru Selatan",
    "Kepulauan Aru",
    "Maluku Barat Daya",
    "Maluku Tengah",
    "Maluku Tenggara",
    "Maluku Tenggara Barat",
    "Seram Bagian Barat",
    "Seram Bagian Timur",
    "Tual"
  ],
  "Maluku Utara": [
    "Halmahera Barat",
    "Halmahera Selatan",
    "Halmahera Tengah",
    "Halmahera Timur",
    "Halmahera Utara",
    "Kepulauan Sula",
    "Pulau Morotai",
    "Pulau Taliabu",
    "Ternate",
    "Tidore Kepulauan"
  ],
  "Papua Barat": [
    "Fakfak",
    "Kaimana",
    "Manokwari",
    "Manokwari Selatan",
    "Maybrat",
    "Pegunungan Arfak",
    "Raja Ampat",
    "Sorong",
    "Sorong",
    "Sorong Selatan",
    "Tambrauw",
    "Teluk Bintuni",
    "Teluk Wondama"
  ],
  "Papua": [
    "Asmat",
    "Biak Numfor",
    "Boven Digoel",
    "Deiyai",
    "Dogiyai",
    "Intan Jaya",
    "Jayapura",
    "Jayapura",
    "Jayawijaya",
    "Keerom",
    "Kepulauan Yapen",
    "Lanny Jaya",
    "Mamberamo Raya",
    "Mamberamo Tengah",
    "Mappi",
    "Merauke",
    "Mimika",
    "Nabire",
    "Nduga",
    "Paniai",
    "Pegunungan Bintang",
    "Puncak",
    "Puncak Jaya",
    "Sarmi",
    "Supiori",
    "Tolikara",
    "Waropen",
    "Yahukimo",
    "Yalimo"
  ]
};

export const categories = [
    {
        name: 'Elektronik',
        subcategories: ['Smartphone', 'Laptop & Komputer', 'Tablet', 'TV & Audio', 'Kamera & Fotografi', 'Gaming', 'Aksesoris Elektronik', 'Peralatan Rumah']
    },
    {
        name: 'Fashion',
        subcategories: ['Pakaian Pria', 'Pakaian Wanita', 'Sepatu Pria', 'Sepatu Wanita', 'Tas & Dompet', 'Aksesoris Fashion', 'Jam Tangan', 'Kacamata', 'Perhiasan']
    },
    {
        name: 'Rumah & Taman',
        subcategories: ['Makanan & Minuman', 'Furniture & Dekorasi Rumah', 'Kebutuhan Taman & Outdoor', 'Peralatan Bangunan & Material', 'Perlengkapan Rumah & Dapur', 'Elektronik Rumah Tangga']
    },
    {
        name: 'Mobil',
        subcategories: ['Mobil Bekas', 'Aksesori Mobil', 'Audio Mobil', 'Spare Part Mobil', 'Velg dan Ban', 'Truk & Kendaraan Komersial']
    },
    {
        name: 'Motor',
        subcategories: ['Motor Bekas', 'Aksesoris Motor', 'Helm', 'Spare Part Motor']
    },
    {
        name: 'Properti',
        subcategories: ['Dijual: Rumah & Apartemen', 'Disewakan: Rumah & Apartemen', 'Tanah', 'Indekos', 'Dijual: Bangunan Komersil', 'Disewakan: Bangunan Komersial']
    },
    {
        name: 'Jasa & Lowongan Kerja',
        subcategories: ['Lowongan Kerja', 'Cari Pekerjaan', 'Jasa']
    },
    {
        name: 'Handphone & Gadget',
        subcategories: ['Handphone', 'Aksesoris Handphone & Tablet', 'Fotografi & Videografi', 'Games & Console', 'Komputer & Laptop', 'Televisi, Audio & Aksesoris']
    },
    {
        name: 'Hobi & Olahraga',
        subcategories: ['Alat Musik & Aksesoris', 'Alat & Pakaian Olahraga', 'Sepeda, Skuter & Aksesoris', 'Kesenian & Handicraft', 'Buku Cetak & Digital', 'Koleksi & Mainan Hobi', 'Musik & Film', 'Hewan Peliharaan & Aksesoris']
    },
    {
        name: 'Keperluan Pribadi',
        subcategories: ['Adat & Rohani', 'Kesehatan, Perawatan & Kecantikan', 'Tiket & Voucher']
    },
    {
        name: 'Perlengkapan Bayi & Anak',
        subcategories: ['Fashion Bayi & Anak', 'Perlengkapan Ibu & Bayi', 'Boneka & Mainan Anak', 'Buku Anak-anak', 'Stroller, Bouncer & Carrier']
    },
    {
        name: 'Kantor & Industri',
        subcategories: ['Alat Keamanan & Keselamatan', 'Peralatan Kantor & Stationery', 'Perlengkapan Usaha', 'Mesin & Keperluan Industri']
    },
    {
        name: 'Buku & Edukasi',
        subcategories: ['Buku Pelajaran', 'Novel & Fiksi', 'Buku Non-Fiksi', 'Komik & Manga', 'Buku Anak', 'Kamus & Ensiklopedia', 'Alat Tulis', 'Perlengkapan Sekolah', 'Kursus & Tutorial']
    },
    {
        name: 'Olahraga',
        subcategories: ['Fitness & Gym', 'Sepak Bola', 'Basket', 'Badminton', 'Tenis', 'Renang', 'Lari & Jogging', 'Bersepeda', 'Outdoor Sports']
    },
    {
        name: 'Barang Gratis',
        subcategories: ['Barang Rumah Tangga']
    },
    {
        name: 'Lainnya',
        subcategories: ['Hewan Peliharaan']
    }
];
