ALTER TYPE public.category_type ADD VALUE 'Elektronik';
ALTER TYPE public.category_type ADD VALUE 'Fashion';
ALTER TYPE public.category_type ADD VALUE 'Rumah & Taman';
ALTER TYPE public.category_type ADD VALUE 'Mobil';
ALTER TYPE public.category_type ADD VALUE 'Motor';
ALTER TYPE public.category_type ADD VALUE 'Properti';
ALTER TYPE public.category_type ADD VALUE 'Jasa & Lowongan Kerja';
ALTER TYPE public.category_type ADD VALUE 'Handphone & Gadget';
ALTER TYPE public.category_type ADD VALUE 'Hobi & Olahraga';
ALTER TYPE public.category_type ADD VALUE 'Keperluan Pribadi';
ALTER TYPE public.category_type ADD VALUE 'Perlengkapan Bayi & Anak';
ALTER TYPE public.category_type ADD VALUE 'Kantor & Industri';
ALTER TYPE public.category_type ADD VALUE 'Buku & Edukasi';
ALTER TYPE public.category_type ADD VALUE 'Olahraga';
ALTER TYPE public.category_type ADD VALUE 'Barang Gratis';
ALTER TYPE public.category_type ADD VALUE 'Lainnya';
ALTER TYPE public.category_type ADD VALUE 'Smartphone';
ALTER TYPE public.category_type ADD VALUE 'Laptop & Komputer';
ALTER TYPE public.category_type ADD VALUE 'Tablet';
ALTER TYPE public.category_type ADD VALUE 'TV & Audio';
ALTER TYPE public.category_type ADD VALUE 'Kamera & Fotografi';
ALTER TYPE public.category_type ADD VALUE 'Gaming';
ALTER TYPE public.category_type ADD VALUE 'Aksesoris Elektronik';
ALTER TYPE public.category_type ADD VALUE 'Peralatan Rumah';
ALTER TYPE public.category_type ADD VALUE 'Pakaian Pria';
ALTER TYPE public.category_type ADD VALUE 'Pakaian Wanita';
ALTER TYPE public.category_type ADD VALUE 'Sepatu Pria';
ALTER TYPE public.category_type ADD VALUE 'Sepatu Wanita';
ALTER TYPE public.category_type ADD VALUE 'Tas & Dompet';
ALTER TYPE public.category_type ADD VALUE 'Aksesoris Fashion';
ALTER TYPE public.category_type ADD VALUE 'Jam Tangan';
ALTER TYPE public.category_type ADD VALUE 'Kacamata';
ALTER TYPE public.category_type ADD VALUE 'Perhiasan';
ALTER TYPE public.category_type ADD VALUE 'Makanan & Minuman';
ALTER TYPE public.category_type ADD VALUE 'Furniture & Dekorasi Rumah';
ALTER TYPE public.category_type ADD VALUE 'Kebutuhan Taman & Outdoor';
ALTER TYPE public.category_type ADD VALUE 'Peralatan Bangunan & Material';
ALTER TYPE public.category_type ADD VALUE 'Perlengkapan Rumah & Dapur';
ALTER TYPE public.category_type ADD VALUE 'Elektronik Rumah Tangga';
ALTER TYPE public.category_type ADD VALUE 'Mobil Bekas';
ALTER TYPE public.category_type ADD VALUE 'Aksesori Mobil';
ALTER TYPE public.category_type ADD VALUE 'Audio Mobil';
ALTER TYPE public.category_type ADD VALUE 'Spare Part Mobil';
ALTER TYPE public.category_type ADD VALUE 'Velg dan Ban';
ALTER TYPE public.category_type ADD VALUE 'Truk & Kendaraan Komersial';
ALTER TYPE public.category_type ADD VALUE 'Motor Bekas';
ALTER TYPE public.category_type ADD VALUE 'Aksesoris Motor';
ALTER TYPE public.category_type ADD VALUE 'Helm';
ALTER TYPE public.category_type ADD VALUE 'Spare Part Motor';
ALTER TYPE public.category_type ADD VALUE 'Dijual: Rumah & Apartemen';
ALTER TYPE public.category_type ADD VALUE 'Disewakan: Rumah & Apartemen';
ALTER TYPE public.category_type ADD VALUE 'Tanah';
ALTER TYPE public.category_type ADD VALUE 'Indekos';
ALTER TYPE public.category_type ADD VALUE 'Dijual: Bangunan Komersil';
ALTER TYPE public.category_type ADD VALUE 'Disewakan: Bangunan Komersial';
ALTER TYPE public.category_type ADD VALUE 'Lowongan Kerja';
ALTER TYPE public.category_type ADD VALUE 'Cari Pekerjaan';
ALTER TYPE public.category_type ADD VALUE 'Jasa';
ALTER TYPE public.category_type ADD VALUE 'Handphone';
ALTER TYPE public.category_type ADD VALUE 'Aksesoris Handphone & Tablet';
ALTER TYPE public.category_type ADD VALUE 'Fotografi & Videografi';
ALTER TYPE public.category_type ADD VALUE 'Games & Console';
ALTER TYPE public.category_type ADD VALUE 'Komputer & Laptop';
ALTER TYPE public.category_type ADD VALUE 'Televisi, Audio & Aksesoris';
ALTER TYPE public.category_type ADD VALUE 'Alat Musik & Aksesoris';
ALTER TYPE public.category_type ADD VALUE 'Alat & Pakaian Olahraga';
ALTER TYPE public.category_type ADD VALUE 'Sepeda, Skuter & Aksesoris';
ALTER TYPE public.category_type ADD VALUE 'Kesenian & Handicraft';
ALTER TYPE public.category_type ADD VALUE 'Buku Cetak & Digital';
ALTER TYPE public.category_type ADD VALUE 'Koleksi & Mainan Hobi';
ALTER TYPE public.category_type ADD VALUE 'Musik & Film';
ALTER TYPE public.category_type ADD VALUE 'Hewan Peliharaan & Aksesoris';
ALTER TYPE public.category_type ADD VALUE 'Adat & Rohani';
ALTER TYPE public.category_type ADD VALUE 'Kesehatan, Perawatan & Kecantikan';
ALTER TYPE public.category_type ADD VALUE 'Tiket & Voucher';
ALTER TYPE public.category_type ADD VALUE 'Fashion Bayi & Anak';
ALTER TYPE public.category_type ADD VALUE 'Perlengkapan Ibu & Bayi';
ALTER TYPE public.category_type ADD VALUE 'Boneka & Mainan Anak';
ALTER TYPE public.category_type ADD VALUE 'Buku Anak-anak';
ALTER TYPE public.category_type ADD VALUE 'Stroller, Bouncer & Carrier';
ALTER TYPE public.category_type ADD VALUE 'Alat Keamanan & Keselamatan';
ALTER TYPE public.category_type ADD VALUE 'Peralatan Kantor & Stationery';
ALTER TYPE public.category_type ADD VALUE 'Perlengkapan Usaha';
ALTER TYPE public.category_type ADD VALUE 'Mesin & Keperluan Industri';
ALTER TYPE public.category_type ADD VALUE 'Buku Pelajaran';
ALTER TYPE public.category_type ADD VALUE 'Novel & Fiksi';
ALTER TYPE public.category_type ADD VALUE 'Buku Non-Fiksi';
ALTER TYPE public.category_type ADD VALUE 'Komik & Manga';
ALTER TYPE public.category_type ADD VALUE 'Buku Anak';
ALTER TYPE public.category_type ADD VALUE 'Kamus & Ensiklopedia';
ALTER TYPE public.category_type ADD VALUE 'Alat Tulis';
ALTER TYPE public.category_type ADD VALUE 'Perlengkapan Sekolah';
ALTER TYPE public.category_type ADD VALUE 'Kursus & Tutorial';
ALTER TYPE public.category_type ADD VALUE 'Fitness & Gym';
ALTER TYPE public.category_type ADD VALUE 'Sepak Bola';
ALTER TYPE public.category_type ADD VALUE 'Basket';
ALTER TYPE public.category_type ADD VALUE 'Badminton';
ALTER TYPE public.category_type ADD VALUE 'Tenis';
ALTER TYPE public.category_type ADD VALUE 'Renang';
ALTER TYPE public.category_type ADD VALUE 'Lari & Jogging';
ALTER TYPE public.category_type ADD VALUE 'Bersepeda';
ALTER TYPE public.category_type ADD VALUE 'Outdoor Sports';
ALTER TYPE public.category_type ADD VALUE 'Barang Rumah Tangga';
ALTER TYPE public.category_type ADD VALUE 'Hewan Peliharaan';